export const capitals = [
    "Kabul",
    "Mariehamn",
    "Tirana",
    "Algiers",
    "Pago Pago",
    "Andorra la Vella",
    "Luanda",
    "Saint John's",
    "Buenos Aires",
    "Yerevan",
    "Oranjestad",
    "Canberra",
    "Vienna",
    "Baku",
    "Nassau",
    "Manama",
    "Dhaka",
    "Bridgetown",
    "Minsk",
    "Brussels",
    "Belmopan",
    "Porto-Novo",
    "Thimphu",
    "La Paz",
    "Sucre",
    "Sarajevo",
    "Gaborone",
    "Brasilia",
    "Road Town",
    "Bandar Seri Begawan",
    "Sofia",
    "Ouagadougou",
    "Gitega",
    "Praia",
    "Phnom Penh",
    "Yaounde",
    "Ottawa",
    "Bangui",
    "N'Djamena",
    "Santiago",
    "Beijing",
    "Bogota",
    "Moroni",
    "Avarua",
    "Zagreb",
    "Havana",
    "Willemstad",
    "Nicosia",
    "Prague",
    "Kinshasa",
    "Copenhagen",
    "Djibouti",
    "Roseau",
    "Santo Domingo",
    "Quito",
    "Cairo",
    "San Salvador",
    "Malabo",
    "Asmara",
    "Tallinn",
    "Mbabane",
    "Addis Ababa",
    "Torshavn",
    "Suva",
    "Helsinki",
    "Paris",
    "Cayenne",
    "Papeete",
    "Libreville",
    "Banjul",
    "Tbilisi",
    "Berlin",
    "Accra",
    "Gibraltar",
    "Athens",
    "Nuuk",
    "Saint George's",
    "Basse-Terre",
    "Guatemala City",
    "Saint Peter Port",
    "Conakry",
    "Bissau",
    "Georgetown",
    "Port-au-Prince",
    "Tegucigalpa",
    "Hong Kong",
    "Budapest",
    "Reykjavik",
    "Delhi",
    "Jakarta",
    "Tehran",
    "Baghdad",
    "Dublin",
    "Douglas",
    "Jerusalem",
    "Rome",
    "Yamoussoukro",
    "Kingston",
    "Tokyo",
    "Saint Helier",
    "Amman",
    "Almaty",
    "Nairobi",
    "Tarawa",
    "Pristina",
    "Kuwait",
    "Bishkek",
    "Vientiane",
    "Riga",
    "Beirut",
    "Maseru",
    "Monrovia",
    "Tripoli",
    "Vaduz",
    "Vilnius",
    "Luxembourg",
    "Macau",
    "Antananarivo",
    "Lilongwe",
    "Kuala Lumpur",
    "Male",
    "Bamako",
    "Valletta",
    "Majuro",
    "Fort-de-France",
    "Nouakchott",
    "Port Louis",
    "Mamoudzou",
    "Mexico City",
    "Chisinau",
    "Monaco",
    "Ulan Bator",
    "Podgorica",
    "Rabat",
    "Maputo",
    "Nay Pyi Taw",
    "Windhoek",
    "Kathmandu",
    "Amsterdam",
    "Noumea",
    "Wellington",
    "Managua",
    "Niamey",
    "Abuja",
    "Pyongyang",
    "Skopje",
    "Saipan",
    "Oslo",
    "Muscat",
    "Islamabad",
    "Panama",
    "Port Moresby",
    "Asuncion",
    "Lima",
    "Manila",
    "Warsaw",
    "Lisbon",
    "Doha",
    "Brazzaville",
    "Saint-Denis",
    "Bucharest",
    "Moscow",
    "Kigali",
    "Gustavia",
    "Basseterre",
    "Castries",
    "Marigot",
    "Kingstown",
    "Apia",
    "Sao Tome",
    "Riyadh",
    "Dakar",
    "Belgrade",
    "Freetown",
    "Singapore",
    "Bratislava",
    "Ljubljana",
    "Honiara",
    "Mogadishu",
    "Cape Town",
    "Pretoria",
    "Seoul",
    "Juba",
    "Madrid",
    "Colombo",
    "Khartoum",
    "Paramaribo",
    "Stockholm",
    "Bern",
    "Damascus",
    "Taipei",
    "Dushanbe",
    "Dodoma",
    "Bangkok",
    "Dili",
    "Lome",
    "Nuku'alofa",
    "Port of Spain",
    "Tunis",
    "Istanbul",
    "Ashgabat",
    "Funafuti",
    "Charlotte Amalie",
    "Kampala",
    "Kyiv",
    "Abu Dhabi",
    "London",
    "Washington",
    "Montevideo",
    "Tashkent",
    "Port-Vila",
    "Caracas",
    "Hanoi",
    "Sanaa",
    "Lusaka",
    "Harare"
  ];